---
name: Lint

on:
  push:
  pull_request:

permissions: read-all

jobs:
  super-lint:
    name: Lint with Super-Linter
    runs-on: ubuntu-latest

    ############################################
    # Grant status permission for MULTI_STATUS #
    ############################################
    permissions:
      contents: read
      packages: read
      statuses: write

    steps:
      # Checks out a copy of your repository on the ubuntu-latest machine
      - name: Checkout code
        uses: actions/checkout@v5
        with:
          # Make sure the actual branch is checked out when running on PR
          # ref: ${{ github.event.pull_request.head.sha }}
          # Full git history needed to get proper list of changed files
          fetch-depth: 0

      # Runs the Super-Linter action
      - name: Run Super-Linter on new changes
        uses: github/super-linter/slim@v7
        env:
          DEFAULT_BRANCH: main
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MARKDOWN_CONFIG_FILE: .markdownlint.json
          PYTHON_RUFF_CONFIG_FILE: .ruff.toml
          # Only check new or edited files
          VALIDATE_ALL_CODEBASE: false
          # Fail on errors
          DISABLE_ERRORS: false
          # Both options below should be already covered by ruff
          VALIDATE_PYTHON_ISORT: false
          VALIDATE_PYTHON_FLAKE8: false
          VALIDATE_PYTHON_BLACK: false
          VALIDATE_PYTHON_MYPY: false
          VALIDATE_PYTHON_PYLINT: false
          VALIDATE_PYTHON_PYINK: false
